# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bitwarden-secrets-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bitwarden-secrets-manager:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/ripplefcl/bws-cache
              tag: v2.0.0@sha256:3a06cbe835ceb39cdbbc8c0bb933cb40e920052404aff4bdfe13aec4094fdac1
            env:
              SECRET_TTL: 3600
              DEBUG: "true"
              ORG_ID:
                valueFrom:
                  secretKeyRef:
                    name: bitwarden-access-token
                    key: ORG_ID
            # probes:
            #   liveness:
            #     enabled: false
            # #     custom: false
            # #     spec:
            # #       httpGet:
            # #         path: /heartbeat
            # #         port: 5000
            # #       initialDelaySeconds: 15
            # #       periodSeconds: 30
            # #       failureThreshold: 3
            #   readiness:
            #     enabled: false
            # #     custom: true
            # #     spec:
            # #       httpGet:
            # #         path: /health
            # #         port: 5000
            # #       initialDelaySeconds: 15
            #   startup:
            #     enabled: false
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources: &resources
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
