apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:N2jm7nH4Ra8NRu8THzAQOf7XpUtWbn6GVJ+TWIvcaydy2erE,iv:WWN1+cmz1MTG6nxn7/e1lUdJKVg5tIk544IqCkBw+Xs=,tag:RFkskpbIbczyNXiba4cEng==,type:str]
    credentials.json: ENC[AES256_GCM,data:TXC6wcKE2obE7mMDsZzejyXDCV+V0SVc+0TyRrqN1+kNIGfDe5gjZkj4Djd4s0BC/9UunAvhGamkGjUi04xt/1BTxm99dhCl9j0qy+Dauy2deIetx9FsiP87QOXBwKczw+luhCpvYyLQ5Li/2R27hTvhhdUAXyJ3waAfzJbEMT9DnWYyhY4sSvjKzID3MiCOPVRsVZYMWFHoBRs9Ax/fkPBo/A6oyCTfsIVSh7dJDQ==,iv:peiL9WEPt02eSHaK4T7Ida+IpQoskLe1m8i2Phw7U3I=,tag:n5YaV6RBSONfeAKlOv9MHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQ053NmRxNTRhR1Rxd0hu
            YzA2dlNkR0dBdGE0REZlcXF2RGxUaDdSQWhrCm9EblZ2S0pKMnRqSlRYTFFremF0
            WHIxcUJUQzExSkw1eCt5TUwxNmdYZ00KLS0tIFdpUk52azlSWm5hVjRmRStsaytD
            V3hHWFBFTFFFcEJST0hJYXg1TGgvOWMKOTgqaqcY28JOXupI0R4LftiyZjbXpb38
            psGRmJgLxBwcDzpBuF2V0peRRvVZOtfn5Rmhiin2YsQl1vP3ti+XPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T10:39:57Z"
    mac: ENC[AES256_GCM,data:qahXkIcE7/oPWCsVxCi/fJWsJRywucZLHzjkil3AyDhL96JJ7nLFeN/uQ38ntCMvhGUBeVgBvUXhGSBWSs/aObqA4BiqgGhOEYNXN4MPAGvdMpkyza6vJ3AACyzclha1l4lEcqE6HKIZdmQ/7NBy5DFFlm7mo1vWSL0pbY1OGAY=,iv:oS5lSumlKITQVuTIcGJHbL73a1+ef4ERR/adjsxJU1Y=,tag:uFbPXasGf7vi8dvOuG1uig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
