apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:s2Qu7Y9i9bOxcmL1LEG//vWtbt9bbEm3g+vWSDqIWkE5JAQw,iv:Rd+Gg1w/416siae3Ubj61gC2CHwrfAOJXTobM/LU9sk=,tag:Kv/YEe97BoDiLycDckG7MA==,type:str]
    credentials.json: ENC[AES256_GCM,data:MZH5Br/cnPAHypWmzt3jPb/NEEj1+8RW1Ofxb5AHhZ0Plgw1WhsQxuNOXHdb3d4mZ/eQxXzPK4IcXNcmcTHoPX0s1opJ0PxMaRiWucv5XqkLXgaywsS12YqExuBWnZyezk1/+pkZ8aq8tak+6w668IJ6xuq+YUBwDU0MCvJyP8INMK1zJfX56rteb8rTdR3VCh8iCrwv3m0K5ALeliIMyD5PJz89ZS2c4XE6Gc/SvQ==,iv:LM16AgHsk2XTXPk7dM1MOB439cG0/it2w+hapfr5f8Y=,tag:7XIb/ddRRrR7uCV6Z+tbIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDRXRzVFNW1LUXB0TURr
            OWxCU1lrK1FlRHFUNWFhYThodEZiVXp0Vmk0CjgrelVYeHc1RzZoc2JUUmNobUxV
            UTg4dERQWXRGU0xlOHJFKzhCVTFsMFUKLS0tIFlzNTlyWk9pUC81VmFMRmFva3JJ
            YVFQUEZkUTk0OENoUmI1WEdxL2l2ejAKxWotju2VJdNPD7VEBJ+lo4yZWxGzNeVo
            Hzx3oXUelRWefcJqhHbeIqJ0Dmu0Q2FwvrKvz+mo85WxxWkoNAaeHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T11:06:58Z"
    mac: ENC[AES256_GCM,data:nvCtuqiMyjsKccrCQlPauDWz8Z44YpvQSGTaTJABXUHqSqSmVfitAbtY2UKgfI5CgOe387TFN+eg0bDPXUiKis9qnrtg66KrN4QE2R64vLcTHVdCJTRrbguJBnxAgAfASijaVTiERMg72USXtS1VXcTrUEKB/9nsGuDJbbmiqc0=,iv:8HqlafNnBpUj7gUtrqc5ZzLoYBCc37fnUWbJyLiT77U=,tag:hcJtIZF9TtGMKa0Zgo3CTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
