---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    controllers:
      stirling-pdf:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.36.5@sha256:d03441da7f63d19b4af5e9f30770938dd4ea2697a31cd2151016049c82624b75
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              DOCKER_ENABLE_SECURITY: false
              SECURITY_ENABLE_LOGIN: false
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 500Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
          - host: "{{ .Release.Name }}.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      configs:
        enabled: true
        type: emptyDir
      logs:
        enabled: true
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
