apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DjxGNgiCkHxPfFRZ0q6YTV5PNLl+flESYWLShv7FelAhP8PQrKarTg==,iv:lvGLZga7hLVRvPOjvaHixP/pnC2+yGdVaKSnmjOrYO4=,tag:VGj9PVkkLQcnHXpCZt6Kvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dUhJSmhzMktSdi9yUVFt
            YUc0ei94WGxweTZqSlZSYWRsMDRWeHdwRlZnCmJBY2F6Y0NaTWxxbGRzRnMxcXRL
            S2t1eTFvYzIxWEVhN21VU202bzh6dDAKLS0tIG5HUmJFdnBubEVMV0RqVmZSNkp2
            cUl3WGVyYkNRSkpHMGtScWEwMzVxcU0KtzFZduaY8TvHbKwBB8qlQ1bYH7RKs87p
            lUGiwjNV6BjGpnVC3VwECfDIooCaUCYlFlDhUDA2tXoxTcUbpAstFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T22:58:52Z"
    mac: ENC[AES256_GCM,data:elHAq5E6sJemyOPEzJFJmFnDSBdsPjVfUaqqunV86EseKhhMAcJ/ABCP/rNsRTCfB2F1a42OISLI9C4vHmq/nMdQYgZMeGyOkFeHEr8OkzA1z1TbRl3BRAcp8tcKKe0nL+miYntYrboXu7TCMzREWK0heB39n6W7szz5ZO9Qyss=,iv:lSkYwzpzhpZJj134q5QILadRjV6wYD5agWQp2SaBWN4=,tag:5WwSY9xQ2xhWTtq8ref4og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
