---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181

    DNS: 172.16.1.1
    addons:
      vpn:
        # -- Enable the VPN if you want to route through a VPN.
        # You might also want to set VPN_BLOCK_OTHER_TRAFFIC to true
        # for extra safeness in case the VPN does connect
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.39.0
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: "off"
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: DOT
            value: "off"
        envFrom:
          - secretRef:
              name: pod-gateway-secret
        resources:
          requests:
            cpu: 10m
            memory: 128M
          limits:
            memory: 128M
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        networkPolicy:
          enabled: false
      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 10M
          limits:
            memory: 50M

    # Testing gluetun sidecar approach
    # routed_namespaces:
    #   - downloads

    settings:
      # -- IPs not sent to the POD gateway but to the default K8S.
      # Multiple CIDRs can be specified using blanks as separator.
      # Example for Calico: ""172.22.0.0/16 172.24.0.0/16"
      #
      # This is needed, for example, in case your CNI does
      # not add a non-default rule for the K8S addresses (Flannel does).
      NOT_ROUTED_TO_GATEWAY_CIDRS: ${CLUSTER_PODS_CIDR} ${CLUSTER_SVCS_CIDR} ${CR_LAN_CIDR} ${GH_LAN_CIDR} ${PW_LAN_CIDR}

      # -- Prevent non VPN traffic to leave the gateway
      VPN_BLOCK_OTHER_TRAFFIC: true

      # -- If using a VPN, interface name created by it
      VPN_INTERFACE: wg0

      # -- Traffic to these IPs will be sent through the K8S gateway
      VPN_LOCAL_CIDRS: ${CLUSTER_PODS_CIDR} ${CLUSTER_SVCS_CIDR} ${CR_LAN_CIDR} ${GH_LAN_CIDR} ${PW_LAN_CIDR}

      # -- If VPN_BLOCK_OTHER_TRAFFIC is true, allow VPN traffic over this port
      VPN_TRAFFIC_PORT: "51820"

      # -- Vxlan ID to use
      VXLAN_ID: 43

      # -- VXLAN needs an /24 IP range not conflicting with K8S and local IP ranges
      VXLAN_IP_NETWORK: 172.16.1

      # -- DNS queries to these domains will be resolved by K8S DNS instead of
      # the default (typically the VPN client changes it)
      DNS_LOCAL_CIDRS: "local"

    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5

      # -- string: Selector for namespace. boolean
      # All pods in this namespace will get evaluated by the webhook.
      namespaceSelector:
        label: vpn.home.arpa/routed-gateway

      # -- boolean: Default behaviour for new PODs in the evaluated namespace
      # if true then the gatewayLabel and gatewayAnnotations will not be utilized and the
      # gateway will be injected into every pod in the namespace
      gatewayDefault: true

      # -- boolean: gatewayLabel and gatewayAnnotation controls the label/annotation key of which the value,
      #   by default, must be 'true' on the pod in order for the gateway sidecar to be injected.
      gatewayLabel: vpn.home.arpa/enabled
      gatewayAnnotation: vpn.home.arpa/enabled

      # -- string: When a value is configured for the gatewayLabelValue or setGatewayAnnotationValue,
      #   the value of the label and/or annotation set on the gatewayLabel or gatewayAnnotation
      #   must match the gatewayLabelValue or setGatewayAnnotationValue instead of the default 'true'.
      # gatewayLabelValue:
      # gatewayAnnotationValue:
