---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: angelnu
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.10.0@sha256:d728eac85f750b37c96a0dafd038561ea4b8035857802be1128ea9b19c61e181

    DNS: 172.16.1.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.39.0
        env:
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: FIREWALL_ENABLED_DISABLING_IT_SHOOTS_YOU_IN_YOUR_FOOT
            value: "off"
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: DOT
            value: "off"
        envFrom:
          - secretRef:
              name: pod-gateway-secret
        resources:
          requests:
            cpu: 10m
            memory: 128M
          limits:
            memory: 128M
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        networkPolicy:
          enabled: false
      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 10M
          limits:
            memory: 50M
    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "51820"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
    routed_namespaces: ["downloads"]
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.10.0@sha256:a8ed630613de277244dfe203cd11d05905d7eeba8d8c41e399b02ee9a847b2f5

      # -- string: Selector for namespace. boolean
      # All pods in this namespace will get evaluated by the webhook.
      namespaceSelector:
        label: routed-gateway

      # -- boolean: Default behaviour for new PODs in the evaluated namespace
      # if true then the gatewayLabel and gatewayAnnotations will not be utilized and the
      # gateway will be injected into every pod in the namespace
      gatewayDefault: true

      # -- boolean: gatewayLabel and gatewayAnnotation controls the label/annotation key of which the value,
      #   by default, must be 'true' on the pod in order for the gateway sidecar to be injected.
      gatewayLabel: routed-gateway
      gatewayAnnotation:

      # -- string: When a value is configured for the gatewayLabelValue or setGatewayAnnotationValue,
      #   the value of the label and/or annotation set on the gatewayLabel or gatewayAnnotation
      #   must match the gatewayLabelValue or setGatewayAnnotationValue instead of the default 'true'.
      gatewayLabelValue:
      gatewayAnnotationValue:
