---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: bazarr-secret
    template:
      engineVersion: v2
      data:
        # App
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        BAZARR_API_KEY: "{{ .BAZARR_API_KEY }}"
  dataFrom:
    - extract:
        key: bazarr
    - extract:
        key: plex
---
