apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:79ofyAXI27+H7SSZwg==,iv:I+WyXMPpNuON8cvg5hWwcgkeMrzOpL+ftdH5SW2Fh4c=,tag:ifgwjcZehPe7JDp5ciZLQA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:G72QOUxfR1vIGxNUSfSWLy8mpjYa,iv:F1IAoTSfWCu4mn10AzONccZ2Ricb7qif6+E7rflJcA0=,tag:d6rReM6BclwTKd6nI5ztkA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KMJhhCiMNv3BzAtG4MkMzleC43X1i0pCHkWU0Ua80w/toTIP,iv:hxN/ifM5+QbrMI0+oZSggRMDKutvw7kYE77pGjI7W7M=,tag:PxXnu4dxQmsdZ7QdD5+MTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Wlk3S3JKbjRONmQ2NEhR
            ekJOQTdxbzkzN2o4VUxITGxzUlJrL2VGZ3pVCjgvdHRKRXhGMFRPbndwNlVIcW9P
            WmllclR5eEd1QWtabmRZQkFob3N3cUkKLS0tIFJ1Zm45YjFrVkJZMXVOOU52aW4v
            ams3eEFJNWRPSkxvbHBhOEJLNWErdGsKeULnC/69obaiTTw97/I5fuU5tI6BYWbB
            +ZOiPw//Qq24WStQNzNFf76y5Vpqzb7nnZCL/aJWDgVRxtWML7IHSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T22:16:48Z"
    mac: ENC[AES256_GCM,data:Xh3DRdXnuX6TFvwCepSNmr/R6JjosXjsHst8tiQDCI/4vGp9LknLcxjd3r0JABRhs2jtC3pDgC7xqJfO4C5nZkXzpWJpbPlMyS6cNwcyzXD/zySAVpBDxsfbt/xM5/H64Sx9supGuXWF6dA0XTRXi8wrL5fWsSKJktfi9AD7nVY=,iv:uY912hKFmCPHI4VfrmhKYWgyMt7jwSnJy6V189yYXGY=,tag:NpEHT/PVt/nfDsMTTLKssg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
