apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:t6o3FcA1U/ZZniJKQg==,iv:wpoZdjLChzEJfv56XZyww8GW/x5Q4tCU0//m7Aa09SA=,tag:DmiyHBIQMnbjbMnzBcA7gQ==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:2+iZuHAg9RX0dxaDpSYHPbOn,iv:toIez/FLRqqsjev6BYsrL6qrQf3kSlyvlAsd1LNE3tw=,tag:AJrJnKyZHMvP4vdoK7C4sQ==,type:str]
    SECRET_STORAGE_SERVER: ENC[AES256_GCM,data:Cf5OyTN84FIlyxcfBYNJtJxVPPLWD42JIs2ruLg=,iv:+1BiPcMspcmI98PVDTtZvnM2Tyq5/azs1neatx5sPIA=,tag:h7IKJxvIGeJnQ9ZWdEonGA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:s+z4md8bURFDjq+n4A096FosxM/5,iv:9Xxc0oDbM4Ip9eG0AeIg9tJa34G9jUi8gIK+8vDZmZA=,tag:DBz+4tbOQQS+w2jDmlq9Rg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cMC1xSPaar+Dusec0YAny2z0wWBhxky+5CWOh+DRShmJjk6z,iv:nu95qW0FBi5J5pbkpA1dFl0ruGECwhwMZtjPIehskPM=,tag:ehoEr6C7oT9Yy1y+nTa0oQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:5ructVYWWA700Z3R+Q==,iv:L/GjCNc3rTcQOmzLayRJYdYWflHhXgCAmk0Qtx9kSDQ=,tag:3gi3f9PJTy0gUpAtq9HNIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK1JwYXNRSVplWU50Qldk
            L0hmclNrNXdlaDN3Qi80cXJ3cXhYczFCZWdFCk9CTGlsVmtJMEp5c0xpSVVhdkdt
            WWdhRTJkRlVXbXQ0YXY0d3lNeVl2SmcKLS0tIEgwOVQ5T0JnUkRsK1BQRzI5SkFs
            SWJ2elA2SzY2WSszNE5QVFg2Mk16NlEKSzNSJgR/vXZMyARKG3SSzoxGEIMxgEgK
            Xrpyva9iEu3EP/8VPigIWEyWKLlaTHzFUQOwXByq64MmCDWyGOelCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-20T22:20:05Z"
    mac: ENC[AES256_GCM,data:lrbYYHAQM+vmPdveheTJODQmP9sOp1dnlraqQph92w/oYQSrOghOMwDIJli5mlkwNfIGAPOSbxzeSf0FceW6mQAV59sHmYgIIfuvuWDQKJO/ErfNvNjZ8bSg/5s+akiItuTY2hcg56jqDhA/D+/ZC2lNuiI4iVtoUp3vWtKeCkY=,iv:/51/GsJK8sxPK/hjr6MF0vTWATM2bVG2MlVldHG/GD8=,tag:S08OIDQ1PRLYidcw7/SWaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
