---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hoarder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager

  target:
    name: hoarder-secret
    template:
      engineVersion: v2
      data:
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        NEXT_PUBLIC_SECRET: "{{ .NEXT_PUBLIC_SECRET }}"
  dataFrom:
    - extract:
        key: hoarder
    - extract:
        key: meilisearch
