---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app satisfactory
  namespace: games
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      satisfactory:
        type: statefulset
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/wolveix/satisfactory-server
              tag: v1.9.5@sha256:88507d728a683714a4fac54d881a8f80db418509bc7db7bad660deda64b72247
            env:
              TZ: "${TIMEZONE}"
              ROOTLESS: "true"
              AUTOPAUSE: "true"
              AUTOSAVEINTERVAL: "60"
              AUTOSAVENUM: "30"
              AUTOSAVEONDISCONNECT: "true"
              CRASHREPORT: "false"
              MAXPLAYERS: "5"
              MAXTICKRATE: "120" # default is a low 30
              NETWORKQUALITY: "3" # 0-3, 3 is Ultra (default)
              TIMEOUT: "300"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                memory: 4Gi
              limits:
                memory: 16Gi
    service:
      app:
        enabled: true
        controller: *app
        type: LoadBalancer
        allocateLoadBalancerNodePorts: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "satisfactory.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: "${SVC_SATISFACTORY_ADDR}"
        ports:
          game-udp:
            enabled: true
            primary: true
            port: 7777
            protocol: UDP
          game-tcp:
            enabled: true
            port: 7777
            protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 6
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      server-cache:
        enabled: true
        existingClaim: "sf-gamedata"
        globalMounts:
          - path: /config/gamefiles
