apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:KWug0qJR1sfl0m1ok0fBgoGTedQXCOqO9vIOclErpqo=,iv:PMgTFlu6OLDh5JbXtuEsZCPkMbu94MHuS/soFr9N//w=,tag:aVD9oj9C6lDe4Az3nbXEbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdjdJVFkzUTVVOU1MMndM
            MVZScGVYL0pXMjlWSzZ5empUMytMVmZmdUg4CkVHUzdhZDNrdHZLUUk0WGwzNzU2
            dEp3UU1vRTBtZHZsRldNSE5RclZLem8KLS0tIDZpdDBuOE9rN3h1R2phYkRNUWVm
            OGtROU11QmhKOEJVRXlTTmUzWUM4ZFkKC6R1sr3VLrhlHNFwWvxzh0/HykqUSXEV
            Oa7xME43WY6M6UroF5y9abmnIGHl/8l4YDLcrhczpMF1/MCmvR+jRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-10T10:39:57Z"
    mac: ENC[AES256_GCM,data:p6XV5cPLoZQER/CXiXFqDJDpsIecsVSF2Kzv2cW3NR7f2PKua15pC6XJz87VB995JHy1E9T3pgrARdIc2wmc4MbJjo6tfcoiUoql7dZRYiujd+6nC4u1Rig4Elu86L98933hOD8FkSp5SD7hYlK79+kRryKrCcw0s5pWAjLWb20=,iv:lgz2HRGOTevBQw75ScbltkAKaTjwdim9gCmwOunk9aw=,tag:nncyolQkhjRPow9GrU6+Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
