apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Wf0zZhMawIO0QHGY77g1GkGMrkxfyNNodBlcTfJqkRM=,iv:WyzsX6IHgONVgvB2Or98RTAuXXrH6do8ztJ9vLZP3lk=,tag:f2bioHtNzUAB7xsoOrGmPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u7cp8qhkcepqupfdtgxs94x5nuwm7ygnr0jfsqnpdfu7e7fns4mq796djl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdWpIS1J6U08zZHl3UjYw
            SU85YzlzTE1WcWk3dmRBS0lDejlnWGJGd1ZZCmphaVFFbFFqcWp0QnI3S3dJUUVX
            dkc3dGdGRnBTeHlTVFVJM1lrd2ZZaHMKLS0tIG5XV1FsWlNrK3VzakZaT0U1T1RH
            YkhqamNvVzNHY2FXK09pUjVKdk9CblEK+nwCBJ3ixX/yQrfux5q/D1mqqhAaD7jS
            AhEwBrJ3qxo5Ru49fO/+jaS5uvSrA3BCBRBMiB60B26SujPT3TxK4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T22:58:52Z"
    mac: ENC[AES256_GCM,data:NY3Jq9hXO0w5NvFqyR+H1v2GY/hPGluVg+vMW885DjV2F+iGuP0X5Qdy/CaWhb2/mAfdIKUpgXVUn+lHRbjr3UwYFT/iLmyciplcO8qzMQG2gNjyWEq3/fjWhzcdytYEtuKdmBBuNeGTyn3zkMK+HAoxJN+QMIA/SdzWnbgWt/g=,iv:tPY16zE+6mMHfMIecRweo2UX09/FJI5RSxMuFKlvOjE=,tag:k7SIiloKk/pvalmsP7hBqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
